### ISSUE TITLE
[!] Cannot load main LinkedIn page

### ISSUE THREAD

**Issue by quistuipater** [SpiderLabs/social_mapper#22]
$ python social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict
    $ [!] Cannot load main LinkedIn page

Using Python 2.7, [fixed "ImportError: No module named modules"](https://github.com/SpiderLabs/social_mapper/pull/8), and my LinkedIn credentials are correct.

The error report is from `def loadPage(client, url, data=None):`, **client** is: `<urllib2.OpenerDirector instance at 0x1093affc8>` and **url** is: `https://www.linkedin.com/`

**Comment by Green-Wolf** [comment]
Can you post some more info please if this is still an issue? OS & Full trace.

**Comment by quistuipater** [comment]
I'm on MacOS 10.13.6. I added ```import traceback``` at the top of **social_mapper.py** and ```traceback.print_exc()``` before ```print "[!] Cannot load main LinkedIn page"``` and got:
```Traceback (most recent call last):
  File "social_mapper.py", line 822, in loadPage
    response = client.open(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:661)>
[!] Cannot load main LinkedIn page```

**Comment by quistuipater** [comment]
I'm on macOS 10.13.6. I added ```import traceback``` at the top of **socail_mapper.py** and ```traceback.print_exc()``` before ```print "[!] Cannot load main LinkedIn page"``` and got:

```Traceback (most recent call last):
  File "social_mapper.py", line 822, in loadPage
    response = client.open(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:661)>
[!] Cannot load main LinkedIn page```

**Comment by quistuipater** [comment]
Note to self ... do not click on the ```Close and comment``` button by accident; there's is no undo.

**Comment by Green-Wolf** [comment]
This is strange, i've tested on OSX and it works fine. I think this may be local for your system. Try installing another version of openssl with brew. Try reinstalling urllib2 with pip. Otherwise i'm not sure, so try running it on linux in a VM? Feel free to reopen if those don't work
