### ISSUE TITLE
Phyton2.7: import facebook | Phyton3: [-] Error Filling out Facebook Profiles [-]

### ISSUE THREAD

**Issue by ThallesCanela** [SpiderLabs/social_mapper#29]
Note:
1 - Running with Phyton3: Not the same module that is inside the "modules" folder. I already installed facebook-sdk and the problem continues.
$ python3 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder -m fast -fb -tw
Traceback (most recent call last):
  File "social_mapper.py", line 13, in <module>
    import facebook
ModuleNotFoundError: No module named 'facebook'

2 - Running with Phyton2.7: I believe this problem is due to the lack of the facebook module (message displayed when executed with Phyton3).
$ python2.7 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder -m fast -fb -tw
[-] Error Filling out Facebook Profiles [-]
Message: connection refused

[-]
Traceback (most recent call last):
  File "social_mapper.py", line 1112, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 218, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "./modules/twitterfinder.py", line 18, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

3 - Different folders:
3.1 - Folder: social_mapper_ (social_mapper.py adapted to run with Phyton3)
3.2 - Folder: social_mapper (default files, without changes, downloaded in GitHub)
4 - The installation of the required dependencies were installed successfully, without problems.
5 - No other file was created (except __init__.py in the modules folders), no other file was changed (except the social_mapper.py files to run in different versions of Phyton)
=================================== Em PT-BR ===================================
Obs.:
1 - Executando com o Phyton3: Não é o mesmo modulo que está dentro da pasta "modules". Já instalei o facebook-sdk e o problema continua.
$ python3 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder -m fast -fb -tw
Traceback (most recent call last):
  File "social_mapper.py", line 13, in <module>
    import facebook
ModuleNotFoundError: No module named 'facebook'

2 - Executando com o Phyton2.7: Acredito que este problema é devido a falta do modulo facebook (mensagem exibida quando executado com o Phyton3).
$ python2.7 social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder -m fast -fb -tw
[-] Error Filling out Facebook Profiles [-]
Message: connection refused

[-]
Traceback (most recent call last):
  File "social_mapper.py", line 1112, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 218, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "./modules/twitterfinder.py", line 18, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

3 - Pastas diferentes:
3.1 - Pasta: social_mapper_ (social_mapper.py adaptado para executar com o Phyton3)
3.2 - Pasta: social_mapper (arquivos padrões, sem alterações, baixados no GitHub)
4 - A instalação das dependência requeridas foram instaladas com sucesso, sem problemas.
5 - Não foi criado nenhum outro arquivo (exceto o __init__.py nas pastas modules), não foi alterado nenhuma outro arquivo (exceto os arquivos social_mapper.py para executar em diferentes versões do Phyton)

**Comment by Xx-KaAzZ-xX** [comment]
Hi, I have exactly the same problem when I try to launch a facebook research with an image folder :

```
python social_mapper.py -f imagefolder -i img/ -m fast -fb
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!
```
I've tried to force the imagefolder directory in the code here by replacing args.input by a global variable that I have set earlier but it didn't work (line 927) :
```
     if not args.input.endswith("/"):
         args.input = args.input + "/"
     exit=False
     for filename in os.listdir(args.input):

```

**Comment by JayVmyhub** [comment]
Hey guys,

getting error by mapping LI photos:

`python social_mapper.py -f imagefolder -i /root/mountedWIN10/ -m fast -li
Traceback (most recent call last):
  File "social_mapper.py", line 1134, in <module>
    peoplelist = fill_linkedin(peoplelist)
  File "social_mapper.py", line 394, in fill_linkedin
    LinkedinfinderObject = linkedinfinder.Linkedinfinder(showbrowser)
  File "./modules/linkedinfinder.py", line 17, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
`

**Comment by SamehEtaiwi** [comment]
Same problem with me,  please help :( 

[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Error 2] The system cannot find the file specified
Program install error!
[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:00.020000

**Comment by SamehEtaiwi** [comment]
and I'm using win10 so Xvfb is not available on windows.

**Comment by JayVmyhub** [comment]
after doing above solution:

Traceback (most recent call last):
  File "social_mapper.py", line 1134, in <module>
    peoplelist = fill_linkedin(peoplelist)
  File "social_mapper.py", line 394, in fill_linkedin
    LinkedinfinderObject = linkedinfinder.Linkedinfinder(showbrowser)
  File "./modules/linkedinfinder.py", line 17, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by e13267212** [comment]
> after doing above solution

Hey i have the same error, do you fix it?
