### ISSUE TITLE
Program install error

### ISSUE THREAD

**Issue by thistehneisen** [SpiderLabs/social_mapper#39]
```
root@SEQ:~/Code/Python/social_mapper# python social_mapper.py -f imagefolder -i ./images -m fast -fb -tw
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 
[-]
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Code/Python/social_mapper/modules/twitterfinder.py", line 14, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! ```

**Comment by LBraccoPutta** [comment]
Install xvfb via **apt** or **apt-get**.
`sudo apt-get install xvfb`
