### ISSUE TITLE
Refusing connection in all services!

### ISSUE THREAD

**Issue by ramramtau** [SpiderLabs/social_mapper#42]
[-] Error Filling out Facebook Profiles [-]
Message: connection refused

[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:01:06.708474

**Comment by thistehneisen** [comment]
```
root@SEQ:~/Code/Python/social_mapper# python social_mapper.py -f imagefolder -i ./images -m fast -fb -tw
[-] Error Filling out Facebook Profiles [-]
Message: connection refused

[-]
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Code/Python/social_mapper/modules/twitterfinder.py", line 18, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```
Same situation.

**Comment by kx2000xx** [comment]
`root@kali:~/Desktop/social_mapper#` python social_mapper.py -f imagefolder -i /root/Desktop/social_mapper/Input-Examples/imagefolder/ -m fast -ig -tw
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Desktop/social_mapper/modules/twitterfinder.py", line 14, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!`



same here but no connection refused!!

**Comment by CoelhoNL** [comment]
> easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!`

Try to install 'xvfb' with apt

**Comment by kx2000xx** [comment]
@CoelhoNL Thank you very much, this problem fixed and now another problem shows up plus it's connection refused like the topic and the same problem @ramramtau 

```
root@kali:~/Desktop/social_mapper# python social_mapper.py -f imagefolder -i /root/Desktop/social_mapper/Input-Examples/imagefolder/ -m fast -tw
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Desktop/social_mapper/modules/twitterfinder.py", line 18, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

```

**Comment by LBraccoPutta** [comment]
@kx2000xx unzip correct (which properly works with your firefox) geckodriver version into /usr/bin/ folder.
If you you use **Firefox 61.0.2**, then unzip geckodriver 0.21.0 into **/usr/bin/**
[
Download geckodriver](https://github.com/mozilla/geckodriver/releases)

**Comment by kx2000xx** [comment]
@LBraccoPutta 

i did and now another problem comes up !!

```
root@kali:~/Desktop/social_mapper# python social_mapper.py -f imagefolder -i /root/Desktop/social_mapper/Input-Examples/imagefolder/ -m fast -tw
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Desktop/social_mapper/modules/twitterfinder.py", line 18, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

**Comment by TADT1909** [comment]
@ramramtau You should install xvfb, firefox (not firefox-esr or something else), geckodriver.
And update them all, of course.

To install offical Firefox:
`sudo add-apt-repository ppa:mozillateam/firefox-next
sudo apt update && sudo apt upgrade`

**Comment by Green-Wolf** [comment]
I think if you downgrade firefox and geckdriver, you need an older version of selenium as well. I would recommend trying what @TADT1909 suggested.

**Comment by lorenzoromani1983** [comment]
having the same problem

**Comment by Green-Wolf** [comment]
Its at a level where it works for various Linux flavours and Mac, so you need to do a few bits and bobs to get in working on your particular version. It's just part of the installation process.
