### ISSUE TITLE
error

### ISSUE THREAD

**Issue by annonymousdevil** [SpiderLabs/social_mapper#53]
command:
python social_mapper.py -f imagefolder -i images  -ig -m fast -s
output:
Traceback (most recent call last):
  File "social_mapper.py", line 1116, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 295, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/root/social_mapper/modules/instagramfinder.py", line 19, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 157, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by Green-Wolf** [comment]
Probably a selenium installation problem. Try running the selenium test script to see if that works.

**Comment by Soutcast** [comment]
`from selenium import webdriver

browser = webdriver.Firefox(executable_path='/usr/bin/geckodriver')
browser.get('http://seleniumhq.org/')`
