### ISSUE TITLE
Selenium error: socialmapper working only with Facebook

### ISSUE THREAD

**Issue by lorenzoromani1983** [SpiderLabs/social_mapper#54]
Hi. So long, I am trying to get it running on Twitter and Facebook (Kali Linux).
ok with Facebook, but with Twitter, Instagram, Linkedin, etc, I get this error:

root@kali:~/Desktop/social_mapper-master# python social_mapper.py -f imagefolder -i ./ -m fast -tw 
Traceback (most recent call last):
  File "social_mapper.py", line 1111, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 217, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/Desktop/social_mapper-master/modules/twitterfinder.py", line 19, in __init__
    self.driver.implicitly_wait(15)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 767, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing 'type' parameter

What next?
tnx

**Comment by Green-Wolf** [comment]
Possibly a problem with your install, people have been reporting to run on Kali you need to install a different version of firefox (non ESR, firefox "normal"). Then you can get the latest version of selenium and geckodriver to work.

**Comment by lorenzoromani1983** [comment]
How can I uninstall Firefox ESR and install the standard Firefox? Is it possible on Kali?

**Comment by lorenzoromani1983** [comment]
this code is not working. If that is a browser issue, why then it works on Facebook and fails on the other socials?

**Comment by lorenzoromani1983** [comment]
Solved, manually updating geckodriver and firefox (non-esr) to latest versions on my kali.
Had to manually add firefox to PATH.

**Comment by Green-Wolf** [comment]
Great, thanks for sharing how you fixed it @lorenzoromani1983
