### ISSUE TITLE
connection refused 

### ISSUE THREAD

**Issue by misterbot28652** [SpiderLabs/social_mapper#63]
python2 social_mapper.py -f imagefolder -i /root/Desktop/images/ -m accurate -ig
Traceback (most recent call last):
  File "social_mapper.py", line 1117, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 296, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/root/scripts/social_mapper/modules/instagramfinder.py", line 20, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by Green-Wolf** [comment]
Looks like a problem with your selenium install, try Kali/Mac with a fresh install following all instructions in the readme
