### ISSUE TITLE
cannot identify image file 'potential_target_image.jpg'

### ISSUE THREAD

**Issue by e13267212** [SpiderLabs/social_mapper#80]
[+] VKontakte Login Page loaded successfully [+]
[+] Vkontakte Login Success [+]

VKontakte Check 1/1 : photo                                cannot identify image file 'potential_target_image.jpg'
cannot identify image file 'potential_target_image.jpg'
cannot identify image file 'potential_target_image.jpg'
cannot identify image file 'potential_target_image.jpg'

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html
 How to fix it? Thanks

**Comment by Green-Wolf** [comment]
Is this with the latest code (last hour or two?)

**Comment by e13267212** [comment]
Don`t know, i use it only 2 hours :( Before ur last update i had another error

**Comment by Green-Wolf** [comment]
Are you able to use the '-s' now to see if the login in successful? I could have broken it 😬

**Comment by e13267212** [comment]
-s don`t work or i don`t know how to use it :smile: 
$ python social_mapper.py -s  -f imagefolder -i ./Input-Examples/imagefolder -vk -m accurate

[+] VKontakte Login Page loaded successfully [+]
[+] Vkontakte Login Success [+]

VKontakte Check 1/1 : photo                                cannot identify image file 'potential_target_image.jpg'
cannot identify image file 'potential_target_image.jpg'
cannot identify image file 'potential_target_image.jpg'

cannot identify image file 'potential_target_image.jpg'


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:03:58.948757

**Comment by e13267212** [comment]
when i use '--showbrowser' but not '-s', it can`t login

**Comment by e13267212** [comment]
Sorry for this spam, bro

**Comment by e13267212** [comment]
New error 'Traceback (most recent call last):
  File "social_mapper.py", line 1133, in <module>
    peoplelist = fill_vkontakte(peoplelist)
  File "social_mapper.py", line 546, in fill_vkontakte
    VkontaktefinderObject = vkontaktefinder.Vkontaktefinder(showbrowser)
  File "/home/e13267212/Загрузки/social_mapper-master/modules/vkontaktefinder.py", line 20, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
'

**Comment by Green-Wolf** [comment]
Hey, no worries, happy to help. 

I just downloaded the latest version and ran it on Mac, i get a small error with one of the targets, but it still works overall. The latest output you posted deffinetly points to something wrong with your selenium/gecko install. Did you mention you put one in usr/bin and one in /usr/local/bin? 

Try putting them both in the same one as i think one is used when running as root, and the other when your using another user?
 
```
$ python social_mapper.py -s -f imagefolder -i ./Input-Examples/imagefolder -vk -m accurate

[+] VKontakte Login Page loaded successfully [+]
[+] Vkontakte Login Success [+]

VKontakte Check 2/3 : Linus Torvalds                                [Errno 2] No such file or directory: '/images/camera_200.png?ava=1'
VKontakte Check 3/3 : Steve Jobs
Linus Torvalds
	Vkontakte: https://vk.com/id221930578

Steve Jobs
	Vkontakte: https://vk.com/id328229396


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:48.212055
```

**Comment by e13267212** [comment]
I put one geckodriver in usr/bin and one in /usr/local/bin, no result the same error

**Comment by e13267212** [comment]
Wow now i get another error: 
Traceback (most recent call last):
  File "social_mapper.py", line 1133, in <module>
    peoplelist = fill_vkontakte(peoplelist)
  File "social_mapper.py", line 546, in fill_vkontakte
    VkontaktefinderObject = vkontaktefinder.Vkontaktefinder(showbrowser)
  File "/home/e13267212/social_mapper/modules/vkontaktefinder.py", line 20, in __init__
    self.driver = webdriver.Firefox()
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 163, in __init__
    log_path=service_log_path)
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
IOError: [Errno 13] Permission denied: 'geckodriver.log'

**Comment by e13267212** [comment]
Traceback (most recent call last):
  File "social_mapper.py", line 1133, in <module>
    peoplelist = fill_vkontakte(peoplelist)
  File "social_mapper.py", line 546, in fill_vkontakte
    VkontaktefinderObject = vkontaktefinder.Vkontaktefinder(showbrowser)
  File "/home/e13267212/social_mapper/modules/vkontaktefinder.py", line 20, in __init__
    self.driver = webdriver.Firefox()
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/e13267212/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

Help :(

**Comment by Green-Wolf** [comment]
I think the best thing might be to just grab a fresh kali install and start again from scratch, following the steps the everyone else is using. You might just have something badly installed on the current version, or somethings gone wrong. I've double checked again and the code is fine, its all to do with  the install process unfortunately!

**Comment by e13267212** [comment]
Thanks, can u tell me how to install selenium? `pip install selenium` right? Sorry for stupid questions

**Comment by Green-Wolf** [comment]
Yeah that should be it! its covered during the pip install -r requirements.txt bit 😄

**Comment by Green-Wolf** [comment]
I'm going to close this as it's definitely an install/setup issue, but feel free to keep posting in here if you need any help, i'll do what i can. Good luck!

**Comment by e13267212** [comment]
> I'm going to close this as it's definitely an install/setup issue, but feel free to keep posting in here if you need any help, i'll do what i can. Good luck!

Thanks, u2

**Comment by Green-Wolf** [comment]
Hi @e13267212, can you find a random person on VK, download their image and name it their name and search for them? Does it find them or is the issue just with your test images?

**Comment by e13267212** [comment]
It can find just standart img (steave jobs, etc.) but other poeple can`t
