### ISSUE TITLE
LinkedIn error

### ISSUE THREAD

**Issue by lavorato** [SpiderLabs/social_mapper#88]
Hello folks! I found an LinkedIn error. I don't know if the LikedIn changed the interface, but the message that I receive are always the same:

`Traceback (most recent call last):
  File "social_mapper.py", line 1123, in <module>
    peoplelist = fill_linkedin(peoplelist)
  File "social_mapper.py", line 384, in fill_linkedin
    LinkedinfinderObject.doLogin(linkedin_username,linkedin_password)
  File "/home/ubuntu/social_mapper/modules/linkedinfinder.py", line 33, in doLogin
    lnkUsername = self.driver.find_element_by_id("session_key-login")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="session_key-login"]`

**Comment by Green-Wolf** [comment]
Hey thanks for flagging this @lavorato, It looks like LinkedIn are using a bit of login jitter so theres 2 types of login page now that seems random. 

I just updated the LinkedIn module and it should try looking for both pages now. Let me know if it sorts it out for you?

**Comment by lavorato** [comment]
Many thanks @Green-Wolf I'll try it again. I tried to solve this issue in the code but unfortunately I did not succeed.

**Comment by Green-Wolf** [comment]
No problem, let me know if this isn't solve and i'll have another look
