### ISSUE TITLE
Instagram Module Error (Mac OS X)

### ISSUE THREAD

**Issue by p4nther1337** [SpiderLabs/social_mapper#89]
I'm having problems with the Instagram module. I'm getting the following error

`Traceback (most recent call last):
  File "social_mapper.py", line 1117, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 296, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/Users/p4nther/social_mapper/modules/instagramfinder.py", line 16, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! `

Anyone know how to fix this???

**Comment by Green-Wolf** [comment]
Hey there @p4nther1337, try having a look through the other issues on this repository by searching for 'Xvfb'. Looks like you can fix it on OSX by installing xquartz:
https://github.com/SpiderLabs/social_mapper/issues/50
Let me know if this doesn't fix it and i'll reopen
