### ISSUE TITLE
Unable to locate element: [id="btn-primary"]

### ISSUE THREAD

**Issue by DocKali** [SpiderLabs/social_mapper#94]
Hi,

I tried to run the tool and I had this error : 

```
Traceback (most recent call last):
  File "social_mapper.py", line 1123, in <module>
    peoplelist = fill_linkedin(peoplelist)
  File "social_mapper.py", line 384, in fill_linkedin
    LinkedinfinderObject.doLogin(linkedin_username,linkedin_password)
  File "/usr/toolz/social_mapper/modules/linkedinfinder.py", line 43, in doLogin
    self.driver.find_element_by_id("btn-primary").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 359, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="btn-primary"]
```
Did LinkedIn change another time their logging page?

Thanks for your help!

**Comment by Green-Wolf** [comment]
Hi @DocKali, you are completely correct, There are issues with LinkedIn and Google Plus at the moment, i'm working on fixing them right now!

**Comment by Green-Wolf** [comment]
& Thank you for making an issue :)!

**Comment by DocKali** [comment]
Thanks for your quick answer @Green-Wolf ! Good luck to fix these issues, I'm waiting for the next pull ;)

**Comment by Green-Wolf** [comment]
Hey @DocKali, I've pushed a fix for your issue with LinkedIn. Would you mind letting me know if it works for you now? Many thanks.

**Comment by DocKali** [comment]
Hey @Green-Wolf, thanks a lot. Your push solved my issue, now LinkedIn is OK in your tool!

Many thanks for your work!
