### ISSUE TITLE
c++: internal compiler error: Morto (program cc1plus)

### ISSUE THREAD

**Issue by cyvitor** [SpiderLabs/social_mapper#97]
I received this error during installation:

`    [  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    c++: internal compiler error: Morto (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    dlib_build/CMakeFiles/dlib.dir/build.make:86: recipe for target 'dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o' failed
    make[2]: *** [dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o] Error 4
    CMakeFiles/Makefile2:140: recipe for target 'dlib_build/CMakeFiles/dlib.dir/all' failed
    make[1]: *** [dlib_build/CMakeFiles/dlib.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-M89K7Q/dlib/setup.py", line 257, in <module>
        'Topic :: Software Development',
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-M89K7Q/dlib/setup.py", line 133, in run
        self.build_extension(ext)
      File "/tmp/pip-install-M89K7Q/dlib/setup.py", line 173, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-M89K7Q/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-GG5W30/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-M89K7Q/dlib/
`

**Comment by cyvitor** [comment]
I solved this, i instaled on debian 9
